### ISSUE TITLE
Babel Runtime is missing

### ISSUE THREAD

**Issue by jakub300** [github-tools/github-release-notes#109]
Steps to reproduce:
1. Install: `npm install github-release-notes -g`
2. Run: `gren changelog`

Result:
```
Jakub-B-iMac:generator-chisel jakubbogucki$ gren changelog
module.js:529
    throw err;
    ^

Error: Cannot find module 'babel-runtime/core-js/object/keys'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jakubbogucki/npm/lib/node_modules/github-release-notes/dist/Program.js:7:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

According to [babel docs](https://babeljs.io/docs/plugins/transform-runtime/): `In most cases, you should install babel-plugin-transform-runtime as a development dependency (with --save-dev). [...] and babel-runtime as a production dependency (with --save). The transformation plugin is typically used only in development, but the runtime itself will be depended on by your deployed/published code.`

**Comment by alexcanessa** [comment]
Thanks @jakub300 we'll try to get this fixed ASAP

**Comment by alexcanessa** [comment]
@jakub300 all fixed 👍
