### ISSUE TITLE
Tags not found

### ISSUE THREAD

**Issue by wellDan28** [github-tools/github-release-notes#132]
Hey all,

I'm trying to run gren release against two specific tags and get the following error :

>  Getting all closed Pull RequestsTypeError: Cannot read property '1' of undefined

I think that this is happens because my repository have plenty of tags, and gren doesn't use paging when request tags from github api.

stacktrace:
>   at Gren._callee11$ (C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\dist\Gren.js:1189:83)
  at tryCatch (C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\node_modules\regenerator-runtime\runtime.js:62:40)
  at Generator.invoke [as _invoke] (C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\node_modules\regenerator-runtime\runtime.js:296:22)
  at Generator.prototype.(anonymous function) [as next] (C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\node_modules\regenerator-runtime\runtime.js:114:21)
  at step (C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
  at C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
  at new Promise (<anonymous>)
  at new F (C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\node_modules\core-js\library\modules\_export.js:35:28)
  at Gren.<anonymous> (C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)
  at Gren._getClosedIssues (C:\Users\dan\AppData\Roaming\nvm\v8.9.3\node_modules\github-release-notes\dist\Gren.js:1210:31)`

**Comment by alexcanessa** [comment]
@wellDan28 actually `gren` does use pagination so that shouldn't really matter.
Let me look into this issue and I'll come back to you !

**Comment by wellDan28** [comment]
I think that what causing this possibly bug is the following code(part of the '_getLastTags' function)
https://github.com/github-tools/github-release-notes/blob/3e6b2e40e20a1abca065bfacad58d25164c1d1db/lib/src/Gren.js#L315-L318
the `this.options.tags.indexOf('all') >= 0 ` clause lets you use paging only if the tags parameter is 'all', so in my case where the tags parameter is two specific versions the paging is not working. 
I tried to remove this clause and it fixed the problem.

**Comment by smira2000** [comment]
I seem to be experiencing this issue as well
```
$ gren release --tags="7.31.0..stage-7.31.0"

🤖  - Generate release notes:
===================================
✔ Releases found: 29
✔ Tags found:
⠋ Getting all closed IssuesTypeError: Cannot read property '1' of undefined
    at Gren._callee11$ (/usr/local/lib/node_modules/github-release-notes/dist/Gren.js:1189:83)
    at tryCatch (/usr/local/lib/node_modules/github-release-notes/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/github-release-notes/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/github-release-notes/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/github-release-notes/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/github-release-notes/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/usr/local/lib/node_modules/github-release-notes/node_modules/core-js/library/modules/_export.js:35:28)
    at Gren.<anonymous> (/usr/local/lib/node_modules/github-release-notes/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Gren._getClosedIssues (/usr/local/lib/node_modules/github-release-notes/dist/Gren.js:1210:31)
```

**Comment by alexcanessa** [comment]
Mmh.. I see @wellDan28 how are you getting on?

**Comment by alexcanessa** [comment]
The paging shouldn't really be a problem, especially when you don't specify `--tags=all`.

I'll try and investigate a bit too.

**Comment by wellDan28** [comment]
@alexcanessa I'll take a look at this issue today and tomorrow. I'll update you.

**Comment by wellDan28** [comment]
I'm working on a fix.

**Comment by wellDan28** [comment]
hey @alexcanessa I'm working on the tests to improve the coverage before we can merge this PR. 
I've got a question about the following test:

https://github.com/github-tools/github-release-notes/blob/3e6b2e40e20a1abca065bfacad58d25164c1d1db/test/Gren.spec.js#L546-L556

I don't understand why is it possible to enter two tags and ignore one of them on the same time.

As far as I understand, if a user enter 2 tags he wants gren to have all the prs/issues/commit between these tags, and because of it he can't ignore a tag that he have asked for. What do you think?

**Comment by alexcanessa** [comment]
@wellDan28 I know it's a bit of a paradox but if you think logic-wise it makes sense: `ignoreTagsWith` filters out tags that contain the specified string.

Are you saying that specifying exactly two tags should trump `ignoreTagsWith`?

**Comment by wellDan28** [comment]
I find it's strange, IMO the only case for using `ignoreTagsWith` should be when `--tags='all'`.
I think that exception should be thrown in the case that I mention above. 

I'l try to explain why this scenario interests me:
In the pr #136  I added a method to validate that in case a user request two tags then these tags are exists after `_getLastTags` fetched the tags from github.

**Comment by alexcanessa** [comment]
>I find it's strange, IMO the only case for using ignoreTagsWith should be when --tags='all'.
I think that exception should be thrown in the case that I mention above

Agreed 👍

**Comment by wellDan28** [comment]
Ok, so I'll change the test in #136 and will open a issue for allow use `ignoreTagsWith` only when `--tags='all'`
