### ISSUE TITLE
GitLab Support

### ISSUE THREAD

**Issue by eoinjordan** [github-tools/github-release-notes#173]
GitLab doesn't appear to be supported:

gren release --token='XXXXXXXXXXXXXX'
/usr/local/lib/node_modules/github-release-notes/node_modules/object-assign-deep/objectAssignDeep.js:77
function executeDeepMerge (target, _objects = [], _options = {}) {
                                            ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/github-release-notes/dist/Gren.js:73:25)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by 130s** [comment]
Was this issue closed because it is invalid? If no I think it's worth keeping it open.

I just saw the similar/same output when I ran `gren` for my Gitlab repo. Tried different arguments but no good.

```
$ npm show gren version
0.0.1    (NOTE I installed it by `sudo npm install github-release-notes -g` on Mar 18, 2019 on Ubuntu 16.04)

$ git checkout -b releasenote/d
Switched to a new branch 'releasenote/d'
$ grep release --username=130s --repo=repo_A
grep: unrecognized option '--username=130s'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
$ gren release --username=130s --repo=repo_A
/usr/local/lib/node_modules/github-release-notes/node_modules/object-assign-deep/objectAssignDeep.js:77
function executeDeepMerge (target, _objects = [], _options = {}) {
                                            ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
        at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
        at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
        at Object.<anonymous> (/usr/local/lib/node_modules/github-release-notes/dist/Gren.js:77:25)
    at Module._compile (module.js:410:26)
        at Object.Module._extensions..js (module.js:417:10)
$ gren release --username=[130s] --repo=[repo_A]
/usr/local/lib/node_modules/github-release-notes/node_modules/object-assign-deep/objectAssignDeep.js:77
function executeDeepMerge (target, _objects = [], _options = {}) {
                                            ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
        at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
        at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
        at Object.<anonymous> (/usr/local/lib/node_modules/github-release-notes/dist/Gren.js:77:25)
    at Module._compile (module.js:410:26)
        at Object.Module._extensions..js (module.js:417:10)
$ gren release --username 130s --repo repo_A
/usr/local/lib/node_modules/github-release-notes/node_modules/object-assign-deep/objectAssignDeep.js:77
function executeDeepMerge (target, _objects = [], _options = {}) {
                                            ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
        at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
        at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
        at Object.<anonymous> (/usr/local/lib/node_modules/github-release-notes/dist/Gren.js:77:25)
    at Module._compile (module.js:410:26)
        at Object.Module._extensions..js (module.js:417:10)
$ gren changelog --generate
/usr/local/lib/node_modules/github-release-notes/node_modules/object-assign-deep/objectAssignDeep.js:77
function executeDeepMerge (target, _objects = [], _options = {}) {
                                            ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
        at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
        at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
        at Object.<anonymous> (/usr/local/lib/node_modules/github-release-notes/dist/Gren.js:77:25)
    at Module._compile (module.js:410:26)
        at Object.Module._extensions..js (module.js:417:10)
$ gren release
/usr/local/lib/node_modules/github-release-notes/node_modules/object-assign-deep/objectAssignDeep.js:77
function executeDeepMerge (target, _objects = [], _options = {}) {
                                            ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
        at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
        at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
        at Object.<anonymous> (/usr/local/lib/node_modules/github-release-notes/dist/Gren.js:77:25)
    at Module._compile (module.js:410:26)
        at Object.Module._extensions..js (module.js:417:10)
```

**Comment by jenlampton** [comment]
I'm seeing the same errors on a GitHub repo. Was anyone able to determine the cause? Have a solution to share?
