### ISSUE TITLE
Cannot generate release notes for a snapshot, i.e what has not been released yet

### ISSUE THREAD

**Issue by eoinjordan** [github-tools/github-release-notes#174]
Is it possible to generate release notes for a snapshot, i.e. all of the work up to the point before a release. 

gren release

🤖  - Generate release notes:
===================================
⠙ Getting the list of releases{ Error: 404 error making request GET https://XXXXX/releases: "Not Found"
    at new ResponseError (/usr/local/lib/node_modules/github-release-notes/node_modules/github-api/dist/components/Requestable.js:50:118)
    at handler (/usr/local/lib/node_modules/github-release-notes/node_modules/github-api/dist/components/Requestable.js:373:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  path: 'XXXXreleases',
  request: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: 
      { Accept: 'application/vnd.github.v3+json',
        'Content-Type': 'application/json;charset=UTF-8',
        Authorization: 'token 2-1xMbXNBZjVkzgZ8k_G',
        'User-Agent': 'axios/0.15.3' },
     method: 'GET',
     url: 'https://XXXX/releases',
     params: { per_page: 30, page: 1 },
     data: undefined,
     responseType: 'json' },
  response: 
   { status: 404,
     statusText: 'Not Found',
     headers:

**Comment by Claudenw** [comment]
This seems like a bug.  I should be able to generate release notes for the very first release.  Can this be done?
