### ISSUE TITLE
Doesn't quite work with Node 10.x.x 

### ISSUE THREAD

**Issue by alexcanessa** [github-tools/github-release-notes#177]

**Comment by tobybot11** [comment]
+1 .. with 10.7.0... i receive the following

```
gren release --data-source=commits --include-messages=all --tags=v0.0.30 --override -P
(node:15059) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'release'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    ...
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
(node:15059) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15059) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by alexcanessa** [comment]
This should work with 0.17.0. @tobybot11 could you double check?

**Comment by tobybot11** [comment]
Thanks! Works on v11.10.0 currently.
