### ISSUE TITLE
exception when attempting to run a release on GHE

### ISSUE THREAD

**Issue by guillermo-menjivar** [github-tools/github-release-notes#208]
Getting the following fatal error when running `gren release -a https://api.my.server.local --token=12344`

```
🤖  - Generate release notes:
===================================
⠼ Getting the list of releasesTypeError: Cannot read property 'status' of undefined
    at handler (/usr/local/lib/node_modules/github-release-notes/node_modules/github-api/dist/components/Requestable.js:366:40)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by videte47** [comment]
am I doing something wrong here ?

**Comment by harvash** [comment]
Same error, using private github:
gren release --tags=all --username=user --repo=https://github.xxxx.com/user/JnksAnsibleSlave.git

🤖  - Generate release notes:
===================================
⠋ Getting the list of releasesTypeError: Cannot read property 'status' of undefined
    at handler (/usr/local/lib/node_modules/github-release-notes/node_modules/github-api/dist/components/Requestable.js:372:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
---
git tag -l                                   
v0.9.2
v0.9.2-alpha
v0.9.3-beta

**Comment by alexcanessa** [comment]
@harvash if you use private repo, remember to use the [`api-url`](https://github-tools.github.io/github-release-notes/options.html#api-url) option.

Said that, looks like @guillermo-menjivar is having this bug even when passing the `-a` option.

The weird thing is that it's failing on the `Requestable`, which means looks like isn't able to connect at all.

**Comment by alexcanessa** [comment]
However, the usage for the `-a` should be something like:

```
$ gren release --api-url=https://MY_ENTERPRISE_DOMAIN/api/v3
```

(Notice the `/api/v3`)

**Comment by harvash** [comment]
🤖  - Generate release notes:
===================================
✔ Releases found: 310325
⠙ Getting tagsTypeError: tags.filter is not a function
    at Gren._callee6$ (/usr/local/lib/node_modules/github-release-notes/dist/Gren.js:679:53)
    at tryCatch (/usr/local/lib/node_modules/github-release-notes/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/github-release-notes/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (/usr/local/lib/node_modules/github-release-notes/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/github-release-notes/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/github-release-notes/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by alexcanessa** [comment]
@harvash Ok, interesting.
Are your tags on origin too?

**Comment by harvash** [comment]
![image](https://user-images.githubusercontent.com/15692862/73677203-c223af00-4683-11ea-906c-77eb462bc4c7.png)

**Comment by harvash** [comment]
Maybe a better indicator?

potb/ansible> git ls-remote --tags origin                                                                   
8eb79e29d289c5a58516fc6658715396bf7207da	refs/tags/v0.9.2
5b676dc324831f5c8afdcd25a3fefbd2876ab80b	refs/tags/v0.9.2-alpha
685c973695e73f0ddf14d12b263cec056facee79	refs/tags/v0.9.2-alpha^{}
c42161449a6737607af27de3c795372c50553b13	refs/tags/v0.9.3-beta

**Comment by harvash** [comment]
Got it working!
gren changelog --api-url=https://github.companyweb.com/api/v3 --tags=all

**Comment by alexcanessa** [comment]
👍 great
