### ISSUE TITLE
Cannot read property of 'status' undefined for enterprise github

### ISSUE THREAD

**Issue by bjhartin** [github-tools/github-release-notes#293]
# Description

When running `changelog` or `release` against enterprise GitHub, it fails with "TypeError: Cannot read property 'status' of undefined" before any tasks run, i.e. before getting tags, etc.

I think this is similar to #120, but seems slightly different.

For example

```bash
$ docker run --rm -v /c/projects/myproject:/repo smartlyio/gren:0.17.0 changelog --api-url=https://api.github.mycompany.com --token=mytoken --username=myteam --repo=myproject

�  - Generate changelog file:
===================================
� - Getting the list of releases
TypeError: Cannot read property 'status' of undefined
    at handler (/usr/local/lib/node_modules/github-release-notes/node_modules/github-api/dist/components/Requestable.js:366:40)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

I have verified that I can get r eleases via the api url:

```bash
curl -k -X GET https://api.github.mycompany.com/repos/myteam/myproject/releases -H 'accept: application/json' -H 'authorization: token mytoken' -H 'content-type: application/json'

{ ... tags ...}
```

I added some logging to Requestable.js and can see its getting ECONNREFUSED but it works via `curl` with the same path/headers.

# Environment

- Enterprise GitHub
- Gren run from docker via smartlyio/gren:0.17.0
- Executed from git-bash via docker cmd above

**Comment by bjhartin** [comment]
Closing this as the underlying problem was a certificate issue and not related to this project.
