### ISSUE TITLE
Always fail with PR have no description

### ISSUE THREAD

**Issue by HatsuneMiku3939** [github-tools/github-release-notes#302]
[lib/src/Gren.js#L1024](https://github.com/github-tools/github-release-notes/blob/master/lib/src/Gren.js#L1024)
```js
const matches = pr.body.match(re);
```

If PR have no description, this line always fail.

```
Getting all merged pull requestsTypeError: Cannot read property 'match' of null
    at _context17.t1 (/home/filepang/.nvm/versions/node/v12.18.2/lib/node_modules/github-release-notes/dist/Gren.js:1760:59)
    at Array.map (<anonymous>)
    at Gren._callee17$ (/home/filepang/.nvm/versions/node/v12.18.2/lib/node_modules/github-release-notes/dist/Gren.js:1773:77)
    at tryCatch (/home/filepang/.nvm/versions/node/v12.18.2/lib/node_modules/github-release-notes/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/filepang/.nvm/versions/node/v12.18.2/lib/node_modules/github-release-notes/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (/home/filepang/.nvm/versions/node/v12.18.2/lib/node_modules/github-release-notes/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/filepang/.nvm/versions/node/v12.18.2/lib/node_modules/github-release-notes/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/filepang/.nvm/versions/node/v12.18.2/lib/node_modules/github-release-notes/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

**Comment by MrHinsh** [comment]
I have a realted issue #320
